name: Build Checker
on: [push, pull_request]

jobs:
  build-check:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install System Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git nim nimble gtk4 libadwaita base-devel

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Program
        run: |
          # 1. تثبيت المكتبة
          nimble install --accept owlkettle
          
          # 2. تحديد مكان الملف وتجميعه في مكانه الأصلي
          # هذا الأمر سيجد الملف أينما كان ويقوم بتجميعه داخل المجلد الخاص به
          TARGET_FILE=$(find . -name "helwan_usb_writer.nim")
          nim c -d:release "$TARGET_FILE"

      - name: Check Result
        run: find . -name "helwan_usb_writer" -type f
