name: Build Checker
on: [push, pull_request]

jobs:
  build-check:
    runs-on: ubuntu-latest
    container: archlinux:latest
    steps:
      - name: Install System Dependencies
        run: |
          pacman -Syu --noconfirm
          pacman -S --noconfirm git nim nimble gtk4 libadwaita base-devel

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build Program
        run: |
          # 1. تثبيت مكتبة owlkettle
          nimble install --accept owlkettle
          
          # 2. الدخول للمجلد الذي رأيناه في ls -R
          cd HelwanUSBWriter
          
          # 3. التجميع (استخدام الملف الذي غيرنا امتداده لـ .nim)
          nim c -d:release --out:../hel-usb-writer src/helwan_usb_writer.nim

      - name: Verify Output
        run: |
          if [ -f "hel-usb-writer" ]; then
            echo "Success: Executable generated!"
            ls -lh hel-usb-writer
          else
            echo "Error: Build failed!"
            exit 1
          fi
